# Generated by Django 5.0.7 on 2024-07-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peets', '0003_coffeetypes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeetypes',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
