# Generated by Django 5.0.7 on 2024-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peets', '0005_alter_coffeetypes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeetypes',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
